version: '2'

volumes:
  db_dev: {}

services:

    database:
        extends:
          file: ./docker/common.yml
          service: database
        env_file:
          - ./docker/environ/local
        ports:
          - 5432:5432
        volumes:
          - db_dev:/var/lib/postgresql/data

    webserver:
        container_name: webserver
        image: webserver_dev
        restart: always
        build:
          context: .
          dockerfile: ./docker/compose/django/dev/Dockerfile
        volumes:
          - .:/app
        links:
          - database
          - frontend
        env_file:
          - ./docker/environ/local
        ports:
          - 8000:8000

    frontend:
        image: frontend_dev
        container_name: frontend
        restart: always
        command: /start.sh
        build:
          context: .
          dockerfile: ./docker/compose/node/dev/Dockerfile
        volumes:
          - .:/app
        ports:
          - 3000:3000
